// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCFVo90-ZdnS46ujTS4z9cjc2TPxH9OYwM',
    appId: '1:1091876128146:web:7907eeabadd56bfabcad4b',
    messagingSenderId: '1091876128146',
    projectId: 'uniapp-73409',
    authDomain: 'uniapp-73409.firebaseapp.com',
    storageBucket: 'uniapp-73409.firebasestorage.app',
    measurementId: 'G-9HBBYWX0QP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC1AWisA6TGkeRM5k9PU4n7jUbR3Kb1Oc0',
    appId: '1:1091876128146:android:e50912fac6e2dd7abcad4b',
    messagingSenderId: '1091876128146',
    projectId: 'uniapp-73409',
    storageBucket: 'uniapp-73409.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCB2vWZFHwD6kzM7ZK2Qu9xC1PjjY_1EZQ',
    appId: '1:1091876128146:ios:e10932c4cd4d3117bcad4b',
    messagingSenderId: '1091876128146',
    projectId: 'uniapp-73409',
    storageBucket: 'uniapp-73409.firebasestorage.app',
    iosBundleId: 'com.example.applicationuni',
  );
}
